### PR TITLE
Require small Docker images

### PR DESCRIPTION
**Pull request by ddeboer**

### CODE REVIEW

**Review by proycon — COMMENTED** [review]
I agree, these are definitely good practices to follow. I'm a bit on the fence whether *MUST* may be a bit too strong here and a *SHOULD* might not already suffice.

**Comment by ddeboer** [comment]
> SHOULD might not already suffice.

I converted this to MUST because now providers have started to deploy their software to CLARIAH (HuC) infrastructure, large Docker images have become a real bottleneck, as @mmisworking already noticed in practice.

Still, I’m okay with reverting this to SHOULD; ‘as small as possible’ is already somewhat vague anyway.

**Comment by proycon** [comment]
Yeah, that's basically my only reason for suggesting 'SHOULD', it's a bit vague what as small as possible means and it'd be very easy to criticize almost any container and suggest it can be even smaller :) And as much as I like and recommend Alpine Linux (which is typically the smallest), I don't want to force it upon tool providers either.

**Comment by ddeboer** [comment]
Fair enough, reverted to SHOULD.

**Pull request merged**
